version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: dify
      POSTGRES_USER: dify
      POSTGRES_PASSWORD: dify
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

  weaviate:
    image: semitechnologies/weaviate:1.23.10
    restart: always
    environment:
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "./data"
      DEFAULT_VECTORIZER_MODULE: "none"
      CLUSTER_HOSTNAME: "node1"
    ports:
      - "8080:8080"

  api:
    image: langgenius/dify-api:latest
    depends_on:
      - db
      - redis
      - weaviate
    environment:
      APP_ENV: production
      DB_USERNAME: dify
      DB_PASSWORD: dify
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: dify
      REDIS_HOST: redis
      REDIS_PORT: 6379
      VECTOR_STORE: weaviate
      WEAVIATE_URL: http://weaviate:8080
      CONSOLE_SECRET_KEY: uma_chave_muito_segura
      WEB_URL: http://localhost:3000
    ports:
      - "5001:5001"

  web:
    image: langgenius/dify-web:latest
    depends_on:
      - api
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:5001
    ports:
      - "3000:3000"

volumes:
  pgdata:
